//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "fii_cvm_properties")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cnpj: String,
    pub reference_date: String,
    pub nome_imovel: String,
    pub endereco: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub area_m2: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub percentual_vacancia: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub percentual_inadimplencia: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub percentual_receitas_fii: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub percentual_locado: Option<f64>,
    pub source: String,
    pub fetched_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
