//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "fii_cvm_monthly")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cnpj: String,
    pub reference_date: String,
    #[sea_orm(column_type = "Double")]
    pub patrimonio_liquido: f64,
    #[sea_orm(column_type = "Double")]
    pub valor_patrimonial_cota: f64,
    pub numero_cotistas: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dividend_yield_mes: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rentabilidade_efetiva_mes: Option<f64>,
    pub source: String,
    pub fetched_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
