//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reit_manual_indicators")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub ticker: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub ffo_per_share: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub affo_per_share: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub occupancy_pct: Option<f64>,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
