//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reit_fundamentals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker: String,
    pub reference_year: i32,
    #[sea_orm(column_type = "Double")]
    pub revenue: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub real_estate_property_net: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub real_estate_property_at_cost: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub stockholders_equity: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub net_income: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub eps_diluted: f64,
    pub source: String,
    pub fetched_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
