//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "suggested_dividends")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub portfolio_id: i32,
    pub asset_id: i32,
    pub payment_date: String,
    #[sea_orm(column_type = "Double")]
    pub amount: f64,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    #[sea_orm(column_type = "Double")]
    pub total: f64,
    pub status: String,
    pub com_date: Option<String>,
    pub source: String,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}