//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "thesis_attachments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub thesis_id: i32,
    pub original_file_name: String,
    pub stored_relative_path: String,
    pub file_size_bytes: i64,
    pub content_type: Option<String>,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::theses::Entity",
        from = "Column::ThesisId",
        to = "super::theses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Theses,
}

impl Related<super::theses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Theses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
