//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub portfolio_id: i32,
    pub asset_id: Option<i32>,
    pub custodia_id: Option<i32>,
    pub transfer_to_custodia_id: Option<i32>,
    pub transaction_type: String,
    pub payment_type: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub quantity: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub unit_price: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub total_value: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub fee: Option<f64>,
    pub transaction_date: String,
    pub notes: Option<String>,
    pub fi_emissor: Option<String>,
    pub fi_indexador: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fi_taxa_percentual: Option<f64>,
    pub fi_data_vencimento: Option<String>,
    pub fi_liquidez: Option<String>,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assets::Entity",
        from = "Column::AssetId",
        to = "super::assets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Assets,
    #[sea_orm(
        belongs_to = "super::custodia::Entity",
        from = "Column::TransferToCustodiaId",
        to = "super::custodia::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Custodia2,
    #[sea_orm(
        belongs_to = "super::custodia::Entity",
        from = "Column::CustodiaId",
        to = "super::custodia::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Custodia1,
    #[sea_orm(
        belongs_to = "super::portfolio::Entity",
        from = "Column::PortfolioId",
        to = "super::portfolio::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Portfolio,
}

impl Related<super::assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assets.def()
    }
}

impl Related<super::portfolio::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Portfolio.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
