//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "watchlist_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub watchlist_id: i32,
    pub asset_id: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub target_price: Option<f64>,
    pub notes: Option<String>,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assets::Entity",
        from = "Column::AssetId",
        to = "super::assets::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Assets,
    #[sea_orm(
        belongs_to = "super::watchlists::Entity",
        from = "Column::WatchlistId",
        to = "super::watchlists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Watchlists,
}

impl Related<super::assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assets.def()
    }
}

impl Related<super::watchlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Watchlists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
