//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "workspace")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::asset_favorites::Entity")]
    AssetFavorites,
    #[sea_orm(has_many = "super::custodia::Entity")]
    Custodia,
    #[sea_orm(has_many = "super::portfolio::Entity")]
    Portfolio,
    #[sea_orm(has_many = "super::watchlists::Entity")]
    Watchlists,
}

impl Related<super::asset_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssetFavorites.def()
    }
}

impl Related<super::custodia::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Custodia.def()
    }
}

impl Related<super::portfolio::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Portfolio.def()
    }
}

impl Related<super::watchlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Watchlists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
